knife bootstrap windows winrm 10.245.240.100 -N SRVCAJDC01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://srvtmgcaj.saraiva.corp:8080
knife bootstrap windows winrm 10.245.240.101 -N SRVCAJDC02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://srvtmgcaj.saraiva.corp:8080
knife bootstrap windows winrm 10.235.0.9 -N LINX-HOMOL.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128


knife bootstrap windows winrm 10.248.244.157 -N SRVAWSETLHOMOL.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.241.135.7 -N SRV-AZURE-SQL01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128

knife bootstrap windows winrm 10.248.92.244 -N SRVCSALEHOMOL.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.57 -N SRVDISTRIB9.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.58 -N SRVDISTRIBEG.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128


knife bootstrap windows winrm 10.248.240.11 -N SRVDIVHPV01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.12 -N SRVDIVHPV02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.51 -N SRVDIVHPV03.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.52 -N SRVDIVHPV04.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.54 -N SRVDIVHPV05.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.84 -N SRVDIVHPV06.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.73 -N SRVDIVHPV07.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.16 -N SRVDIVHPVTEST.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.230 -N SRVDIVIIS01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.231 -N SRVDIVIIS02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.27 -N SRVDIVLISTEN.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.121 -N SRVDIVLYNC.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.127 -N SRVDIVLYNC02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.128 -N SRVDIVLYNC03.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.129.16 -N SRVDIVMBX01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.129.17 -N SRVDIVMBX02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.161 -N SRVDIVMDT01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.236 -N SRVDIVNETWORK.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.123 -N SRVDIVPCHATLYNC.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.180 -N SRVDIVPROFILE.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.72.56 -N SRVDIVQLKVIEW01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.72.57 -N SRVDIVQLKVIEW02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.120.10 -N SRVDIVSAPPWD.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.90 -N SRVDIVSCCM.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.189 -N SRVDIVSQLITOWN.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.164 -N SRVDIVSQLJOBS.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.122 -N SRVDIVSQLLYNC.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.109 -N SRVDIVSQLTFS01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.92 -N SRVDIVSUBCA01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.110 -N SRVDIVTFS.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.82 -N SRVDIVTIVIT.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.200 -N SRVDIVVMM.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.28 -N SRVDIVWDSSAR01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.136.10 -N SRVDIVWEBITOWN1.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.136.11 -N SRVDIVWEBITOWN2.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.170 -N SRVDIVWSUS.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.72.51 -N SRVEGARANTIDA01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.72.52 -N SRVEGARANTIDA02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.72.53 -N SRVEGARANTIDAPR.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.236.1.7 -N SRVETLAPP.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.226 -N SRVHADMTSARAIVA.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.245.240.34 -N SRVHITACHI.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.92.125 -N SRVHOMOLOGEG.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.62 -N SRVHPVWEBSAR01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.63 -N SRVHPVWEBSAR02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.26 -N SRVHS-BROKER03.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.27 -N SRVHS-BROKER04.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.221 -N SRVHSCAS01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.222 -N SRVHSCAS02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.218 -N SRVHSDC01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.96.219 -N SRVHSDC02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.96.220 -N SRVHSDC03.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.240.36 -N SRVHSDTP.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.241 -N SRVHS-FSW.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.32 -N SRVHSHPV03.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.188 -N SRVHS-LGPONTO.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.1 -N SRVHSLIVFISC.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.90 -N SRVHSMAILMININ0.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.217 -N SRVHSMBOX01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.224 -N SRVHSMBOX02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.35 -N SRVHS-PORTALSSO.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.37 -N SRVHS-PROJSEG.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.7 -N SRVHS-STFRONT01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.8 -N SRVHS-STFRONT02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.0.187 -N SRVHS-VCENTER.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.248.10 -N SRVHSWDS01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.240.88 -N SRVHSWDS02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.240.39 -N SRVHSWSUS.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.44 -N SRVHS-XENAPP80.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.46 -N SRVHS-XENAPP81.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.47 -N SRVHS-XENAPP82.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.18 -N SRVHS-XENAPP83.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.45 -N SRVHS-XENAPP90.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.49 -N SRVHS-XENAPP92.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.50 -N SRVHS-XENAPP93.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 172.27.1.28 -N SRVHS-XENPRINT.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.168 -N SRVLOJAHOMOL.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.132.31 -N SRVMONITORING.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.56 -N SRVMUSICA.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.245.240.35 -N SRVNETAPP.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.236.1.6 -N SRVOTDHOMOL.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.132.25 -N SRVPRTG.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.132.11 -N SRVPRTG01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.132.12 -N SRVPRTG02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.238.0.3 -N SRVQLIKVIEW.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.240.150 -N SRVRVARIAVEL.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.118 -N SRVSETUPS.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.56.41 -N SRVSOLR01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.56.42 -N SRVSOLR02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.56.45 -N SRVSOLRZK01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.246.32.15 -N SRVSQLCDBA02.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.246.32.16 -N SRVSQLCDBAPR.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.245.232.12 -N SRVSQLCSALE.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.92.22 -N SRVSQLHOMOL.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.250.76.14 -N SRVSQLLOJASTR.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.246.232.114 -N SRVSQLNFEBAPR01.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.92.98 -N SRVSQLWEB11.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.199 -N SRVSQLWITNESS.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128
knife bootstrap windows winrm 10.248.240.244 -N SRVTEST.saraiva.corp -E prod --winrm-user saraiva.corp\svc_pwsh --winrm-password ProG0x78$ --bootstrap-proxy http://proxy.saraiva.corp:3128



